name: CI Pipeline - Plantilla_Proyecto

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Java 23
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '23'

      - name: Compilar el proyecto y ejecutar tests
        run: mvn clean verify
        
      - name: Generar Javadoc
        run: mvn javadoc:javadoc

      - name: Listar artefactos de build
        run: ls -R target
